base: /api/
baseVariants: {  }
disableStaticFileCache: true
errorHandling: {  }
languages:
  -
    title: API
    enabled: true
    base: /
    typo3Language: ch
    locale: zh_CH.UTF-8
    iso-639-1: zh
    navigationTitle: zh
    hreflang: zh-ch
    direction: ''
    flag: cn
    languageId: '0'
rootPageId: 37
routes: {  }
