<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'EBT\\ExtensionBuilder\\' => array($typo3InstallDir . 'typo3conf/ext/extension_builder/Classes'),
    'ERP\\ErpManagementCollection\\' => array($typo3InstallDir . 'typo3conf/ext/erp_management_collection/Classes'),
    'ERP\\ErpManagementDashboard\\' => array($typo3InstallDir . 'typo3conf/ext/erp_management_dashboard/Classes'),
    'ERP\\ErpManagementDict\\' => array($typo3InstallDir . 'typo3conf/ext/erp_management_dict/Classes'),
    'ERP\\ErpManagementImages\\' => array($typo3InstallDir . 'typo3conf/ext/erp_management_images/Classes'),
    'ERP\\ErpManagementInteraction\\' => array($typo3InstallDir . 'typo3conf/ext/erp_management_interaction/Classes'),
    'ERP\\ErpManagementLogistics\\' => array($typo3InstallDir . 'typo3conf/ext/erp_management_logistics/Classes'),
    'ERP\\ErpManagementNotify\\' => array($typo3InstallDir . 'typo3conf/ext/erp_management_notify/Classes'),
    'ERP\\ErpManagementOrder\\' => array($typo3InstallDir . 'typo3conf/ext/erp_management_order/Classes'),
    'ERP\\ErpManagementProduct\\' => array($typo3InstallDir . 'typo3conf/ext/erp_management_product/Classes'),
    'ERP\\ErpManagementPrupload\\' => array($typo3InstallDir . 'typo3conf/ext/erp_management_prupload/Classes'),
    'ERP\\ErpManagementUser\\' => array($typo3InstallDir . 'typo3conf/ext/erp_management_user/Classes'),
    'ERP\\ErpManagementWallet\\' => array($typo3InstallDir . 'typo3conf/ext/erp_management_wallet/Classes'),
    'ERP\\ErpManagementWorkorder\\' => array($typo3InstallDir . 'typo3conf/ext/erp_management_workorder/Classes'),
    'SFC\\Staticfilecache\\' => array($typo3InstallDir . 'typo3conf/ext/staticfilecache/Classes'),
    'SIMONKOEHLER\\Slug\\' => array($typo3InstallDir . 'typo3conf/ext/slug/Classes'),
    'Sanlilin\\ErpManagementSystemExtension\\' => array($typo3InstallDir . 'typo3conf/ext/erp_management_system_extension/Classes'),
    'Sll\\Common\\' => array($typo3InstallDir . 'typo3conf/ext/common/Classes'),
);
