<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'EBT\\ExtensionBuilder\\' => array($typo3InstallDir . 'typo3conf/ext/extension_builder/Classes'),
    'ERP\\ErpManageProductTemplate\\' => array($typo3InstallDir . 'typo3conf/ext/erp_manage_product_template/Classes'),
    'ERP\\ErpManagementCollection\\' => array($typo3InstallDir . 'typo3conf/ext/erp_management_collection/Classes'),
    'ERP\\ErpManagementDashboard\\' => array($typo3InstallDir . 'typo3conf/ext/erp_management_dashboard/Classes'),
    'ERP\\ErpManagementDict\\' => array($typo3InstallDir . 'typo3conf/ext/erp_management_dict/Classes'),
    'ERP\\ErpManagementImages\\' => array($typo3InstallDir . 'typo3conf/ext/erp_management_images/Classes'),
    'ERP\\ErpManagementProduct\\' => array($typo3InstallDir . 'typo3conf/ext/erp_management_product/Classes'),
    'ERP\\ErpManagementUser\\' => array($typo3InstallDir . 'typo3conf/ext/erp_management_user/Classes'),
    'SFC\\Staticfilecache\\' => array($typo3InstallDir . 'typo3conf/ext/staticfilecache/Classes'),
    'SGalinski\\Lfeditor\\' => array($typo3InstallDir . 'typo3conf/ext/lfeditor/Classes'),
    'Sanlilin\\ErpManagementSystemExtension\\' => array($typo3InstallDir . 'typo3conf/ext/erp_management_system_extension/Classes'),
    'Sll\\Common\\' => array($typo3InstallDir . 'typo3conf/ext/common/Classes'),
);
