#
# Table structure for table 'tx_erpmanagementorder_domain_model_order'
#
CREATE TABLE tx_erpmanagementorder_domain_model_order (

	amazon_order_id varchar(255) DEFAULT '' NOT NULL,
	purchase_date int(11) DEFAULT '0' NOT NULL,
	last_update_date int(11) DEFAULT '0' NOT NULL,
	order_status int(11) DEFAULT '0' NOT NULL,
	fulfillment_channel int(11) DEFAULT '0' NOT NULL,
	ship_service_level int(11) DEFAULT '0' NOT NULL,
	sales_channel varchar(255) DEFAULT '' NOT NULL,
	shipper_name varchar(255) DEFAULT '' NOT NULL,
	shipper_address_line1 text,
	shipper_address_line2 int(11) DEFAULT '0' NOT NULL,
	shipper_address_line3 int(11) DEFAULT '0' NOT NULL,
	shipper_city varchar(255) DEFAULT '' NOT NULL,
	shipper_state_or_region varchar(255) DEFAULT '' NOT NULL,
	shipper_country_code varchar(255) DEFAULT '' NOT NULL,
	shipper_phone varchar(255) DEFAULT '' NOT NULL,
	shipper_address_type varchar(255) DEFAULT '' NOT NULL,
	shipper_is_address_sharing_confidential int(11) DEFAULT '0' NOT NULL,
	currency_code varchar(255) DEFAULT '' NOT NULL,
	amount varchar(255) DEFAULT '' NOT NULL,
	number_of_items_shipped int(11) DEFAULT '0' NOT NULL,
	number_of_items_unshipped int(11) DEFAULT '0' NOT NULL,
	payment_method varchar(255) DEFAULT '' NOT NULL,
	payment_method_details text,
	marketplace_id varchar(255) DEFAULT '' NOT NULL,
	buyer_email varchar(255) DEFAULT '' NOT NULL,
	buyer_name varchar(255) DEFAULT '' NOT NULL,
	shipment_service_level_category varchar(255) DEFAULT '' NOT NULL,
	shipped_by_amazon_t_f_m int(11) DEFAULT '0' NOT NULL,
	order_type varchar(255) DEFAULT '' NOT NULL,
	earliest_ship_date int(11) DEFAULT '0' NOT NULL,
	latest_ship_date int(11) DEFAULT '0' NOT NULL,
	earliest_delivery_date int(11) DEFAULT '0' NOT NULL,
	latest_delivery_date int(11) DEFAULT '0' NOT NULL,
	business_order int(11) DEFAULT '0' NOT NULL,
	prime int(11) DEFAULT '0' NOT NULL,
	global_express_enabled int(11) DEFAULT '0' NOT NULL,
	premium_order int(11) DEFAULT '0' NOT NULL,
	replacement_order int(11) DEFAULT '0' NOT NULL,
	sold_by_a_b int(11) DEFAULT '0' NOT NULL,
	goods int(11) unsigned DEFAULT '0',
	erpuser int(11) unsigned DEFAULT '0',

);
