<?php
return [
    'BE' => [
        'debug' => false,
        'explicitADmode' => 'explicitAllow',
        'installToolPassword' => '$argon2i$v=19$m=65536,t=16,p=2$R3I1UUQxaFFEMGhiSmJ3Vw$lWJktWs5vl4O1byxyuih7YjDjfY0j+XzbwscDY4mrtI',
        'loginSecurityLevel' => 'normal',
        'passwordHashing' => [
            'className' => 'TYPO3\\CMS\\Core\\Crypto\\PasswordHashing\\Argon2iPasswordHash',
            'options' => [],
        ],
    ],
    'DB' => [
        'Connections' => [
            'Default' => [
                'charset' => 'utf8mb4',
                'dbname' => 'DB_erp_whongbin_com',
                'driver' => 'mysqli',
                'host' => '127.0.0.1',
                'password' => '1qaz3edc5tgb',
                'port' => 3306,
                'tableoptions' => [
                    'charset' => 'utf8mb4',
                    'collate' => 'utf8mb4_unicode_ci',
                ],
                'user' => 'root',
            ],
        ],
    ],
    'EXT' => [
        'extConf' => [
            'backend' => 'a:6:{s:14:"backendFavicon";s:0:"";s:11:"backendLogo";s:0:"";s:20:"loginBackgroundImage";s:38:"fileadmin/static_file/img/login_bg.jpg";s:13:"loginFootnote";s:21:"© 2020 by San Li Lin";s:19:"loginHighlightColor";s:7:"#332e2e";s:9:"loginLogo";s:40:"fileadmin/static_file/img/login_logo.svg";}',
            'cart_events' => 'a:1:{s:19:"categoryRestriction";s:0:"";}',
            'extension_builder' => 'a:3:{s:9:"backupDir";s:35:"uploads/tx_extensionbuilder/backups";s:15:"backupExtension";s:1:"1";s:15:"enableRoundtrip";s:1:"1";}',
            'extensionmanager' => 'a:2:{s:21:"automaticInstallation";s:1:"1";s:11:"offlineMode";s:1:"0";}',
            'lfeditor' => 'a:9:{s:16:"beMainModuleName";s:4:"user";s:13:"changeXlfDate";s:1:"1";s:15:"defaultLanguage";s:2:"en";s:17:"editModeExtension";s:1:"1";s:9:"extIgnore";s:23:"/^(CVS|.svn|.git|csh_)/";s:12:"extWhitelist";s:0:"";s:27:"pathAdditionalConfiguration";s:37:"typo3conf/AdditionalConfiguration.php";s:11:"searchRegex";s:60:"/^([a-z0-9_]*locallang[a-z0-9_-]*\\.(php|xml)|[^\\.]*\\.xlf)$/i";s:13:"viewLanguages";s:2:"ch";}',
            'staticfilecache' => 'a:23:{s:18:"backendDisplayMode";s:4:"both";s:9:"boostMode";s:1:"0";s:15:"cacheTagsEnable";s:1:"0";s:23:"clearCacheForAllDomains";s:1:"1";s:12:"debugHeaders";s:1:"0";s:20:"disableInDevelopment";s:1:"0";s:21:"enableGeneratorBrotli";s:1:"0";s:19:"enableGeneratorGzip";s:1:"1";s:23:"enableGeneratorManifest";s:1:"0";s:20:"enableGeneratorPlain";s:1:"0";s:14:"hashUriInCache";s:1:"0";s:20:"htaccessTemplateName";s:61:"EXT:staticfilecache/Resources/Private/Templates/Htaccess.html";s:22:"overrideCacheDirectory";s:0:"";s:25:"rawurldecodeCacheFileName";s:1:"0";s:25:"renameTablesToOtherPrefix";s:1:"0";s:22:"sendCacheControlHeader";s:1:"1";s:47:"sendCacheControlHeaderRedirectAfterCacheTimeout";s:1:"0";s:19:"sendHttp2PushEnable";s:1:"0";s:27:"sendHttp2PushFileExtensions";s:6:"css,js";s:22:"sendHttp2PushFileLimit";s:2:"10";s:21:"useFallbackMiddleware";s:1:"1";s:29:"useReverseUriLengthInPriority";s:1:"1";s:20:"validHtaccessHeaders";s:45:"Content-Type,Content-Language,Link,X-SFC-Tags";}',
        ],
    ],
    'EXTCONF' => [
        'lang' => [
            'availableLanguages' => [
                'ch',
            ],
        ],
    ],
    'EXTENSIONS' => [
        'backend' => [
            'backendFavicon' => '',
            'backendLogo' => '',
            'loginBackgroundImage' => 'fileadmin/static_file/img/login_bg.jpg',
            'loginFootnote' => '© 2020 by San Li Lin',
            'loginHighlightColor' => '#332e2e',
            'loginLogo' => 'fileadmin/static_file/img/login_logo.svg',
        ],
        'cart_events' => [
            'categoryRestriction' => '',
        ],
        'extension_builder' => [
            'backupDir' => 'uploads/tx_extensionbuilder/backups',
            'backupExtension' => '1',
            'enableRoundtrip' => '1',
        ],
        'extensionmanager' => [
            'automaticInstallation' => '1',
            'offlineMode' => '0',
        ],
        'lfeditor' => [
            'beMainModuleName' => 'user',
            'changeXlfDate' => '1',
            'defaultLanguage' => 'en',
            'editModeExtension' => '1',
            'extIgnore' => '/^(CVS|.svn|.git|csh_)/',
            'extWhitelist' => '',
            'pathAdditionalConfiguration' => 'typo3conf/AdditionalConfiguration.php',
            'searchRegex' => '/^([a-z0-9_]*locallang[a-z0-9_-]*\\.(php|xml)|[^\\.]*\\.xlf)$/i',
            'viewLanguages' => 'ch',
        ],
        'staticfilecache' => [
            'backendDisplayMode' => 'both',
            'boostMode' => '0',
            'cacheTagsEnable' => '0',
            'clearCacheForAllDomains' => '1',
            'debugHeaders' => '0',
            'disableInDevelopment' => '0',
            'enableGeneratorBrotli' => '0',
            'enableGeneratorGzip' => '1',
            'enableGeneratorManifest' => '0',
            'enableGeneratorPlain' => '0',
            'hashUriInCache' => '0',
            'htaccessTemplateName' => 'EXT:staticfilecache/Resources/Private/Templates/Htaccess.html',
            'overrideCacheDirectory' => '',
            'rawurldecodeCacheFileName' => '0',
            'renameTablesToOtherPrefix' => '0',
            'sendCacheControlHeader' => '1',
            'sendCacheControlHeaderRedirectAfterCacheTimeout' => '0',
            'sendHttp2PushEnable' => '0',
            'sendHttp2PushFileExtensions' => 'css,js',
            'sendHttp2PushFileLimit' => '10',
            'useFallbackMiddleware' => '1',
            'useReverseUriLengthInPriority' => '1',
            'validHtaccessHeaders' => 'Content-Type,Content-Language,Link,X-SFC-Tags',
        ],
    ],
    'FE' => [
        'baseURL' => 'https://erp.whongbin.com/',
        'debug' => true,
        'dicp' => '',
        'disableNoCacheParameter' => true,
        'icp' => '',
        'loginSecurityLevel' => 'normal',
        'pageNotFound_handling' => 'READFILE:EXT:erp_management_system_extension/Resources/Pages/pages-404.html',
        'pageUnavailable_handling' => 'READFILE:EXT:erp_management_system_extension/Resources/Pages/pages-500.html',
        'passwordHashing' => [
            'className' => 'TYPO3\\CMS\\Core\\Crypto\\PasswordHashing\\Argon2iPasswordHash',
            'options' => [],
        ],
        'sessionTimeout' => 86400,
    ],
    'FILE' => [
        'favicon' => 'static/favicon.ico',
        'logo_sm' => 'static/logo_sm.svg',
    ],
    'FTP' => [
        'app_key' => '0818b92eedfc0200',
        'host' => '148.70.223.113',
        'password' => '6DiXN%aM6!&0',
        'port' => '21',
        'rename' => '1',
        'sec_key' => 'WDP5dSKyE4eKHmq0BgnZr2uOCs90l6Is',
        'sever' => 'http://ftp.whongbin.cn/',
        'timeout' => '90',
        'username' => 'ftpuser',
    ],
    'MAIL' => [
        'transport' => 'sendmail',
        'transport_sendmail_command' => '/usr/sbin/sendmail -t -i',
        'transport_smtp_encrypt' => '',
        'transport_smtp_password' => '',
        'transport_smtp_server' => '',
        'transport_smtp_username' => '',
    ],
    'SYS' => [
        'devIPmask' => '',
        'displayErrors' => 0,
        'encryptionKey' => 'f2470512934c5768373aceefd45f30853dfb1a5af1a246ef95b6b5bab12fd8e75977afff67397ca94aa82674b2e009b6',
        'exceptionalErrors' => 4096,
        'features' => [
            'unifiedPageTranslationHandling' => true,
        ],
        'loginCopyrightWarrantyProvider' => 'San Li Lin',
        'loginCopyrightWarrantyURL' => 'https://www.whongbin.cn/',
        'sitename' => 'ERP平台管理系统',
        'systemLogLevel' => 3,
        'systemMaintainers' => [
            1,
        ],
    ],
    'TRANSLATE' => [
        'app_key' => '0818b92eedfc0200',
        'sec_key' => 'WDP5dSKyE4eKHmq0BgnZr2uOCs90l6Is',
    ],
];
