<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "common"
 *
 * Auto generated by Extension Builder 2019-09-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => '通用配置',
    'description' => '通用配置插件',
    'category' => 'plugin',
    'author' => '三里林',
    'author_email' => 'wanghongbin816@gmail.com',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
